default:
 tags:
    - gitlab-k8-kkm
stages:
 - build

build-ci:
   image: docker:24.0.5
   stage: build
   services:
       - docker:24.0.5-dind
   variables:
     DOCKER_HOST: tcp://docker:2376
     DOCKER_TLS_CERTDIR: "/certs"
     DOCKER_TLS_VERIFY: 1
     DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
   script:
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      - docker --version
      - docker build -t $CI_REGISTRY_IMAGE:vin-${CI_COMMIT_SHORT_SHA} -f Dockerfile .
      - docker push -a $CI_REGISTRY_IMAGE